export const EXCUSES = {
    Trabajo: [ 
        'No puedo ir a trabajar porque tengo una cita médica.',
        'No puedo ir a trabajar porque tengo que cuidar a mi hijo enfermo.',
        'No puedo ir a trabajar porque tengo una reunión importante en otra ciudad.',
        'No puedo ir a trabajar porque mi coche no arranca.',
        'No puedo ir a trabajar porque estoy esperando al técnico de internet.',
        'No puedo ir a trabajar porque tengo fiebre.',
        'No puedo ir a trabajar porque tuve una emergencia familiar.',
        'No puedo ir a trabajar porque se rompió una cañería en mi casa.',
        'No puedo ir a trabajar porque tengo migraña.',
        'No puedo ir a trabajar porque me torcí el tobillo.',
        'No puedo ir a trabajar porque mi hijo tiene una presentación escolar.',
        'No puedo ir a trabajar porque tengo que asistir a un funeral.',
        'No puedo ir a trabajar porque tengo una cita con el dentista.',
        'No puedo ir a trabajar porque me robaron la cartera.',
        'No puedo ir a trabajar porque tuve un problema con el gas.',
        'No puedo ir a trabajar porque estoy esperando una entrega importante.',
        'No puedo ir a trabajar porque tuve una reacción alérgica.',
        'No puedo ir a trabajar porque tuve un accidente doméstico menor.',
        'No puedo ir a trabajar porque estoy esperando una llamada médica.',
        'No puedo ir a trabajar porque se cortó la luz y no puedo salir del edificio.'
    ],

    Pareja: [
        'No puedo salir porque tengo que ayudar a un amigo con un problema personal.',
        'No puedo salir porque tengo que estudiar para un examen importante.',
        'No puedo salir porque tengo una cita médica.',
        'No puedo salir porque tengo que cuidar a mi abuela.',
        'No puedo salir porque tengo un dolor de cabeza fuerte.',
        'No puedo salir porque tengo una entrega del trabajo pendiente.',
        'No puedo salir porque tuve un día muy agotador.',
        'No puedo salir porque tengo una videollamada con mi familia.',
        'No puedo salir porque tengo una clase en línea.',
        'No puedo salir porque estoy cocinando para mañana.',
        'No puedo salir porque mi mascota está enferma.',
        'No puedo salir porque tengo que hacer tareas domésticas.',
        'No puedo salir porque estoy ayudando a un vecino.',
        'No puedo salir porque me siento mal emocionalmente.',
        'No puedo salir porque estoy ayudando a preparar un evento familiar.',
        'No puedo salir porque estoy cuidando a un primo pequeño.',
        'No puedo salir porque tengo que preparar una presentación.',
        'No puedo salir porque tengo que limpiar toda la casa.',
        'No puedo salir porque tengo que quedarme esperando a que reparen algo.',
        'No puedo salir porque tengo que hacer un trámite urgente.'
    ],

    Amigos: [
        'No puedo salir porque tengo que cuidar a mi hermano menor.',
        'No puedo salir porque tengo que trabajar en un proyecto urgente.',
        'No puedo salir porque tengo una reunión familiar.',
        'No puedo salir porque me siento agotado.',
        'No puedo salir porque tengo que hacer compras para la semana.',
        'No puedo salir porque mi pareja no se siente bien.',
        'No puedo salir porque tengo visita inesperada.',
        'No puedo salir porque tengo que terminar de limpiar.',
        'No puedo salir porque tengo una cita con el banco.',
        'No puedo salir porque estoy ayudando a mis padres.',
        'No puedo salir porque estoy acompañando a un amigo al médico.',
        'No puedo salir porque tengo una videollamada importante.',
        'No puedo salir porque tengo que llevar a mi mascota al veterinario.',
        'No puedo salir porque estoy sin transporte.',
        'No puedo salir porque tengo que ordenar documentos importantes.',
        'No puedo salir porque tengo que arreglar una fuga de agua.',
        'No puedo salir porque estoy ayudando con una mudanza.',
        'No puedo salir porque tengo una entrevista virtual.',
        'No puedo salir porque estoy cocinando para un evento.',
        'No puedo salir porque tengo que hacer una entrega personal.'
    ],

    Absurdo: [
        'No puedo salir porque mi perro se comió mis zapatos.',
        'No puedo salir porque me han abducido los extraterrestres.',
        'No puedo salir porque tengo que esperar a que mi planta hable.',
        'No puedo salir porque estoy atrapado en un bucle temporal.',
        'No puedo salir porque un gnomo escondió mis llaves.',
        'No puedo salir porque mi reflejo no me deja en paz.',
        'No puedo salir porque estoy entrenando para un combate contra dragones.',
        'No puedo salir porque el suelo se convirtió en lava.',
        'No puedo salir porque estoy aprendiendo a hablar con los pájaros.',
        'No puedo salir porque perdí una batalla mental contra un yogur.',
        'No puedo salir porque me convertí en estatua por unas horas.',
        'No puedo salir porque estoy esperando que la luna me dé permiso.',
        'No puedo salir porque estoy atrapado en una dimensión paralela.',
        'No puedo salir porque un mago me convirtió en alfombra.',
        'No puedo salir porque estoy negociando con una colonia de hormigas.',
        'No puedo salir porque mi sombra se escapó.',
        'No puedo salir porque tengo que cuidar mi castillo inflable.',
        'No puedo salir porque se me olvidó cómo abrir la puerta.',
        'No puedo salir porque estoy participando en una carrera invisible.',
        'No puedo salir porque un duende me retó a un concurso de miradas.'
    ]
}
